# Initial Azure pipeline for evaluation regarding running a on-premise agent
# which has access to non-published data sets

trigger:
- master

jobs:
- job:
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
        TOXENV: 'py36'
      Python37:
        python.version: '3.7'
        TOXENV: 'py37'
      Python38:
        python.version: '3.8'
        TOXENV: 'py38'
  variables:
    TOXENV: '$(TOXENV)'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - bash: pip install -U tox
    displayName: 'install requirements'

  - bash: tox
    displayName: 'Run tox tests'

  - bash: bash <(curl -s https://codecov.io/bash) -f coverage.xml -f client/coverage/coverage-final.json
    displayName: 'Submit coverage to codecov.io'

# FIXME: remove duplication
- job: dataset_tests
  pool: DataAccess
  variables:
    TOXENV: 'py36'
    LT_TEST_DATA_PATH: '/cachedata/users/clausen/libertem-test-data'
  steps:
  - bash: python3 -m venv venv
    displayName: 'create venv'

  - bash: ./venv/bin/pip install tox
    displayName: 'install tox'

  - bash: ./venv/bin/tox
    displayName: 'Run tox tests'

  - bash: bash <(curl -s https://codecov.io/bash) -f coverage.xml -f client/coverage/coverage-final.json
    displayName: 'Submit coverage to codecov.io'
