# Initial Azure pipeline for evaluation regarding running a on-premise agent
# which has access to non-published data sets

trigger:
- master

- job:
  pool:
    vmImage: 'ubuntu-latest'
  stragegy:
    matrix:
      Python36:
        python.version: '3.6'
        TOXENV: 'py36'
      Python37:
        python.version: '3.7'
        TOXENV: 'py37'
      Python38:
        python.version: '3.8'
        TOXENV: 'py38'
  variables:
    TOXENV: '$(TOXENV)'
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python $(python.version)'
    inputs:
      versionSpec: '$(python.version)'
  - bash: pip install -U tox
    displayName: 'install requirements'

  - bash: tox
    displayName: 'Run tox tests'

  - bash: bash <(curl -s https://codecov.io/bash) -f coverage.xml -f client/coverage/coverage-final.json
    displayName: 'Submit coverage to codecov.io'
